export const CREATE_BOOKS_REQUEST = "CREATE_BOOKS_REQUEST";
export const CREATE_BOOKS_SUCCESS = "CREATE_BOOKS_SUCCESS";
export const CREATE_BOOKS_RESET = "CREATE_BOOKS_RESET";
export const CREATE_BOOKS_ERROR = "CREATE_BOOKS_ERROR";
export const CREATE_BOOKS_CLEAR_ERROR = "CREATE_BOOKS_CLEAR_ERROR";

export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_RESET = "GET_BOOKS_RESET";
export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR";
export const GET_BOOKS_CLEAR_ERROR = "GET_BOOKS_CLEAR_ERROR";


export const UPDATE_BOOKS_REQUEST = "UPDATE_BOOKS_REQUEST";
export const UPDATE_BOOKS_SUCCESS = "UPDATE_BOOKS_SUCCESS";
export const UPDATE_BOOKS_RESET = "UPDATE_BOOKS_RESET";
export const UPDATE_BOOKS_ERROR = "UPDATE_BOOKS_ERROR";
export const UPDATE_BOOKS_CLEAR_ERROR = "UPDATE_BOOKS_CLEAR_ERROR";

export const DELETE_BOOKS_REQUEST = "DELETE_BOOKS_REQUEST";
export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS";
export const DELETE_BOOKS_RESET = "DELETE_BOOKS_RESET";
export const DELETE_BOOKS_ERROR = "DELETE_BOOKS_ERROR";
export const DELETE_BOOKS_CLEAR_ERROR = "DELETE_BOOKS_CLEAR_ERROR";